//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleId { get; set; }
        public Nullable<int> BookId { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int Quantity { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Managers Managers { get; set; }
    }
}
