//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreferences
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GenreId { get; set; }
        public string Author { get; set; }
    
        public virtual Genres Genres { get; set; }
        public virtual Users Users { get; set; }
    }
}
